### ISSUE TITLE
BSTbeam and ma list as input

### ISSUE THREAD

**Issue by JulienNGirard** [AlanLoh/nenupy#11]
BSTbeam returns error when a python list is provided for parameter "ma".

```
>>> bst=BSTbeam(ma=range(10))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/nenupy/beam/bstbeam.py", line 40, in __init__
    self._evalkwargs(kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/nenupy/beam/bstbeam.py", line 298, in _evalkwargs
    self.ma         = kwargs.get('ma', None)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/nenupy/beam/bstbeam.py", line 114, in ma
    raise TypeError("\n\t=== Attribute 'ma' should be an array ===")
TypeError:
	=== Attribute 'ma' should be an array ===
```

**Comment by AlanLoh** [comment]
`range` is a kind of iterator ithin Python3, equivalent to Python2 `xrange`.
It works with `ma=[0,1,2,3,]`
